version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cloudResume-SAM"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-htb2v3pddwqr"
s3_prefix = "cloudResume-SAM"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
