AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Builds DynamoDB table, API Gateway and Lambda service. 

Resources:
  HitCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Lambda/
      Handler: hitCounter.lambda_handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref DynamoDBTable
      Runtime: python3.8
      Events:
        HitCountAPI:
          Type: Api
          Properties:
            Path: /hitCount
            Method: get

  DynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: page_id
        Type: String
      TableName: webPageHits-prod

Outputs:
  HitCountApi:
    Description: "API Gateway endpoint URL for Prod stage for hit count function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hitCount/"